
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null


models:
 - name: DEMO_DB
   description: 'database in snowflake'
   database: DEMO_DB
   schema: PRIVATE
   tables:
     - name: DEMOTABLESOURCE
       description: 'test table'
       columns:
        - name: ID
        - name: A
        - name: B
        - name: C